### ISSUE TITLE
Version 2.0 does not work in IE 11

### ISSUE THREAD

**Issue by chood531** [Alex1990/tiny-cookie#15]
I noticed that after upgrading to version 2.0, this package is no longer working in IE 11.

**Comment by Alex1990** [comment]
Could you provide the error information?

**Comment by Alex1990** [comment]
Today, I tested it in IE11, and it works. So, please tell me more abour how you use it.

**Comment by chood531** [comment]
Hi Alex -

Thanks for your reply.

I installed the package with NPM, and included it using this:

```
import * as Cookies from 'tiny-cookie'
```

I compiled the JavaScript with Webpack using Laravel Mix (https://github.com/JeffreyWay/laravel-mix).

I received a console error in Internet Explorer which I was able to track down to this line: http://d.pr/i/6qAUtj/fVDWaQtK

In my compiled app.js file, I did notice that this line was not getting updated correctly since the ``` was still visible, even though this won't work cross-browser.  

Thinking about this now, perhaps this is more of an issue with Laravel Mix not including the package correctly.  I am far from a Webpack expert (quite the opposite actually), so I am not sure for certain.  I downgraded back to version 1.0 of this plugin to solve my issue for now!

Thanks
