### ISSUE TITLE
Don't use code in `src` folder directly for `module` field in package.json

### ISSUE THREAD

**Issue by foisonocean** [Alex1990/tiny-cookie#16]
I notice in package.json, `module` field is the source code of the project, this means when use a build tools support es6 module (like webpack), the build tools would directly import the source code, which might cause some problems with UglifyJs.
For example, in webpack, when we use a babel loader, we usually exclude the node_modules to improve the build speed, so this means when we import tiny-cookie in webpack, the imported code is still in es6, and UglifyJs doesn't support es6.
My suggestion is we can have another folder(like `lib`), the code should transpile to es5 but it's in es6 module style.
Sorry for my poor english.

**Comment by Alex1990** [comment]
Fixed. And thank you for pointing out it.
