### ISSUE TITLE
Can't remove() cookies set on custom domain

### ISSUE THREAD

**Issue by mogelbrod** [Alex1990/tiny-cookie#17]
I am unable to remove cookies that have been set with a custom domain using the `remove` function, instead having to call `set` with a negative `expires` value.

One solution would be to allow `options` to be passed to `remove`.

```js
tinyCookie.set('test', '1', {expires: 180, domain: 'custom.tld'}) // exposes cookie on *.custom.tld
tinyCookie.remove('test') // doesn't remove cookie
tinyCookie.set('test', '1', {expires: -1, domain: 'custom.tld'}) // removes cookie
```

**Comment by Alex1990** [comment]
Now, from the [v2.1.0](https://github.com/Alex1990/tiny-cookie/tree/v2.1.0#removekey-options) version, the `remove` method supports the second parameter (`options`). You can remove a cookie in the custom/parent domain.

```js
remove('test', { domain: 'parentdomain.com' });
```
