### ISSUE TITLE
Inconsistency with setCookie

### ISSUE THREAD

**Issue by boccob** [Alex1990/tiny-cookie#18]
At the moment `setCookie` takes 4 arguments (only 3 of them are documented though).
`encoder` is an optional argument but for some reason, it's not the last one. And it results in inconsistency:
```js
setCookie('key', 'value'); // encoder == encodeURIComponent
```
but
```js
setCookie('key', 'value', { domain: 'some.domain' }); // encoder == null
```

So, I would suggest to make `encoder` the last argument and also document it.
I can create a PR.

**Comment by Alex1990** [comment]
Can we change the below statement 

https://github.com/Alex1990/tiny-cookie/blob/140a044abf27317270f00cbfbd9d64877f245bff/src/index.js#L57

to

```js
encoder = encodeURIComponent;
```

So, it need not to update the major version. While the `encoder` as the last parameter is more reasonable.

**Comment by boccob** [comment]
I don't see a big issue in major version increment. But if you have any objections (for example if you plan more breaking changes in nearest future, it makes sense to combine them), let's just change this line and update documentation.

Let me know what do you think and I'll create a PR.

**Comment by Alex1990** [comment]
I fixed this bug by changing one line. I'll start to develop the next major version, and you can check the task list #19.
