### ISSUE TITLE
Support SameSite attribute

### ISSUE THREAD

**Issue by khalwat** [Alex1990/tiny-cookie#20]
For security reasons, it would be nice to be able to set the `SameSite` attribute on a cookie as per:

https://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/ssca

https://www.filamentgroup.com/lab/spectre-js-cookie.html

**Comment by Alex1990** [comment]
You can write the below code directly:

```js
import { setCookie } from 'tiny-cookie';

setCookie('foo', 'Foo', { SameSite: 'strict' });
```

I'll add some tests and docs for `SameSite` attributes.

Thank you for reminding me this.

**Comment by Alex1990** [comment]
Updated readme https://github.com/Alex1990/tiny-cookie/commit/443b2f84e88cfb59a154aeba06ca5b79b0f980e0
