### ISSUE TITLE
Option to set httponly?

### ISSUE THREAD

**Issue by rhelsing** [Alex1990/tiny-cookie#23]
Or is this impossible, considering this is a JS lib?

**Comment by Alex1990** [comment]
@rhelsing As far as I know, the `HttpOnly`  flag can only be set with HTTP header `Set-Cookie`. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies

**Comment by rhelsing** [comment]
Thanks for getting back to me.. I may be a little out of my depth here but would this be possible to pass {HttpOnly: true} in the options param?

```javascript
setCookie('dateObject', 'A date object', { expires: date, HttpOnly: true });
```

**Comment by Alex1990** [comment]
So far, this package is only available in the browser. You can check this SO - [Set a cookie to HttpOnly via Javascript](https://stackoverflow.com/questions/14691654/set-a-cookie-to-httponly-via-javascript).
