### ISSUE TITLE
Warning: To load an ES module issue

### ISSUE THREAD

**Issue by laxadev** [Alex1990/tiny-cookie#35]
Since I moved to the latest version 2.4.0 and build the project and try to run it in production mode the site throws this error:
The project is built in SvelteKit.

`(node:49975) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
/Projects/sveltekit-sk/node_modules/tiny-cookie/dist/tiny-cookie.esm.js:168
export { get, getAll, getAll as getAllCookies, get as getCookie, getRaw, getRaw as getRawCookie, isEnabled as isCookieEnabled, isEnabled, remove, remove as removeCookie, set, set as setCookie, setRaw, setRaw as setRawCookie };`

**Comment by laxadev** [comment]
> Hi @laxadev , please try tiny-cookie@^2.4.1

Hi @Alex1990 
I get the following error now:

`ReferenceError: document is not defined
    at Proxy.get (file:///Projects/sveltekit-sk/node_modules/tiny-cookie/dist/tiny-cookie.mjs:115:28)`

**Comment by Alex1990** [comment]
The tiny-cookie can be only called in browser. But it is called in Node.is environment in svelte.
